package Modelos;
// Generated 28/mai/2023 21:10:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int codigoCliente;
     private String nome;
     private String apelido;
     private Date dataNascimento;
     private String bi;
     private String contacto;
     private String email;
     private String endereco;
     private Set vendases = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int codigoCliente, String nome, String apelido, Date dataNascimento, String bi, String contacto, String email, String endereco) {
        this.codigoCliente = codigoCliente;
        this.nome = nome;
        this.apelido = apelido;
        this.dataNascimento = dataNascimento;
        this.bi = bi;
        this.contacto = contacto;
        this.email = email;
        this.endereco = endereco;
    }
    public Cliente(int codigoCliente, String nome, String apelido, Date dataNascimento, String bi, String contacto, String email, String endereco, Set vendases) {
       this.codigoCliente = codigoCliente;
       this.nome = nome;
       this.apelido = apelido;
       this.dataNascimento = dataNascimento;
       this.bi = bi;
       this.contacto = contacto;
       this.email = email;
       this.endereco = endereco;
       this.vendases = vendases;
    }
   
    public int getCodigoCliente() {
        return this.codigoCliente;
    }
    
    public void setCodigoCliente(int codigoCliente) {
        this.codigoCliente = codigoCliente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getBi() {
        return this.bi;
    }
    
    public void setBi(String bi) {
        this.bi = bi;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Set getVendases() {
        return this.vendases;
    }
    
    public void setVendases(Set vendases) {
        this.vendases = vendases;
    }




}


