package Modelos;
// Generated 28/mai/2023 21:10:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private int codigoStock;
     private Viatura viatura;
     private int quantidade;
     private Set vendases = new HashSet(0);

    public Stock() {
    }

	
    public Stock(int codigoStock, Viatura viatura, int quantidade) {
        this.codigoStock = codigoStock;
        this.viatura = viatura;
        this.quantidade = quantidade;
    }
    public Stock(int codigoStock, Viatura viatura, int quantidade, Set vendases) {
       this.codigoStock = codigoStock;
       this.viatura = viatura;
       this.quantidade = quantidade;
       this.vendases = vendases;
    }
   
    public int getCodigoStock() {
        return this.codigoStock;
    }
    
    public void setCodigoStock(int codigoStock) {
        this.codigoStock = codigoStock;
    }
    public Viatura getViatura() {
        return this.viatura;
    }
    
    public void setViatura(Viatura viatura) {
        this.viatura = viatura;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public Set getVendases() {
        return this.vendases;
    }
    
    public void setVendases(Set vendases) {
        this.vendases = vendases;
    }




}


