package Modelos;
// Generated 28/mai/2023 21:10:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Vendas generated by hbm2java
 */
public class Vendas  implements java.io.Serializable {


     private int codigoVenda;
     private Cliente cliente;
     private Funcionario funcionario;
     private Stock stock;
     private int quantidade;
     private BigDecimal precoVenda;

    public Vendas() {
    }

    public Vendas(int codigoVenda, Cliente cliente, Funcionario funcionario, Stock stock, int quantidade, BigDecimal precoVenda) {
       this.codigoVenda = codigoVenda;
       this.cliente = cliente;
       this.funcionario = funcionario;
       this.stock = stock;
       this.quantidade = quantidade;
       this.precoVenda = precoVenda;
    }
   
    public int getCodigoVenda() {
        return this.codigoVenda;
    }
    
    public void setCodigoVenda(int codigoVenda) {
        this.codigoVenda = codigoVenda;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public BigDecimal getPrecoVenda() {
        return this.precoVenda;
    }
    
    public void setPrecoVenda(BigDecimal precoVenda) {
        this.precoVenda = precoVenda;
    }




}


