package Modelos;
// Generated 28/mai/2023 21:10:21 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Viatura generated by hbm2java
 */
public class Viatura  implements java.io.Serializable {


     private int codigoViatura;
     private String marca;
     private String modelo;
     private int numeroPortas;
     private String cilindrada;
     private String potencia;
     private BigDecimal preco;
     private String cor;
     private Set stocks = new HashSet(0);

    public Viatura() {
    }

	
    public Viatura(int codigoViatura, String marca, String modelo, int numeroPortas, String cilindrada, String potencia, BigDecimal preco, String cor) {
        this.codigoViatura = codigoViatura;
        this.marca = marca;
        this.modelo = modelo;
        this.numeroPortas = numeroPortas;
        this.cilindrada = cilindrada;
        this.potencia = potencia;
        this.preco = preco;
        this.cor = cor;
    }
    public Viatura(int codigoViatura, String marca, String modelo, int numeroPortas, String cilindrada, String potencia, BigDecimal preco, String cor, Set stocks) {
       this.codigoViatura = codigoViatura;
       this.marca = marca;
       this.modelo = modelo;
       this.numeroPortas = numeroPortas;
       this.cilindrada = cilindrada;
       this.potencia = potencia;
       this.preco = preco;
       this.cor = cor;
       this.stocks = stocks;
    }
   
    public int getCodigoViatura() {
        return this.codigoViatura;
    }
    
    public void setCodigoViatura(int codigoViatura) {
        this.codigoViatura = codigoViatura;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public int getNumeroPortas() {
        return this.numeroPortas;
    }
    
    public void setNumeroPortas(int numeroPortas) {
        this.numeroPortas = numeroPortas;
    }
    public String getCilindrada() {
        return this.cilindrada;
    }
    
    public void setCilindrada(String cilindrada) {
        this.cilindrada = cilindrada;
    }
    public String getPotencia() {
        return this.potencia;
    }
    
    public void setPotencia(String potencia) {
        this.potencia = potencia;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }
    public String getCor() {
        return this.cor;
    }
    
    public void setCor(String cor) {
        this.cor = cor;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }




}


